export default function sitemap() {
  return [
    {
      url: "https://www.qcentrio.com/offerings/business-value-enhancement-services/generative-ai-solutions-and-offerings",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/business-value-enhancement-services/artificial-intelligence-machine-learning-offerings",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/business-value-enhancement-services/robotic-process-automation-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/erp-solutions-support",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/big-data-services-and-solutions",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/comprehensive-sap-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/custom-software-application-development",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/internet-of-things-solutions",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advanced-technology-solutions/product-engineering-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/epic-advisory-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/audit-and-assurance-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/oracle-cerner-advisory-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/risk-advisory-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/specialty-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/advisory-and-strategic-services/mergers-and-acquisitions-advisory-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/business-optimization-and-analytics-services/data-analytics-and-business-intelligence",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/business-optimization-and-analytics-services/collaboration-and-productivity-solutions",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/business-optimization-and-analytics-services/crm-system-solutions",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/blockchain-advisory-and-offerings/blockchain-integration-and-deployment",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/blockchain-advisory-and-offerings/blockchain-security-and-compliance",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/blockchain-advisory-and-offerings/blockchain-solution-development",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/blockchain-advisory-and-offerings/blockchain-strategy-and-advisory",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/azure-services-and-offerings",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/aws-services-and-offerings",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/cloud-infrastructure-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/continuous-it-support-and-managed-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/cybersecurity-solutions",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/gcp-services-and-offerings",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/offshore-development-centre-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.qcentrio.com/offerings/cloud-infra-and-security-services/salesforce-services",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
